import type { Config } from 'tailwindcss';

export default {
	content: [
		'./src/pages/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/components/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/app/**/*.{js,ts,jsx,tsx,mdx}',
	],
	theme: {
		extend: {
			colors: {
				primary: '#002d37',
				'on-primary': '#ffffff',
				'primary-container': '#1a434e',
				'on-primary-container': '#88afbc',
				'primary-fixed': '#c0e9f7',
				'primary-fixed-dim': '#a5cdda',
				'on-primary-fixed': '#001f27',
				'on-primary-fixed-variant': '#244c57',
				'inverse-primary': '#a5cdda',
				secondary: '#735c00',
				'on-secondary': '#ffffff',
				'secondary-container': '#fed65b',
				'on-secondary-container': '#745c00',
				'secondary-fixed': '#ffe088',
				'secondary-fixed-dim': '#e9c349',
				'on-secondary-fixed': '#241a00',
				'on-secondary-fixed-variant': '#574500',
				tertiary: '#002f1e',
				'on-tertiary': '#ffffff',
				'tertiary-container': '#1a4633',
				'on-tertiary-container': '#86b39b',
				'tertiary-fixed': '#beedd3',
				'tertiary-fixed-dim': '#a2d1b7',
				'on-tertiary-fixed': '#002114',
				'on-tertiary-fixed-variant': '#244f3b',
				error: '#ba1a1a',
				'on-error': '#ffffff',
				'error-container': '#ffdad6',
				'on-error-container': '#93000a',
				surface: '#f8f9fa',
				'surface-dim': '#d9dadb',
				'surface-bright': '#f8f9fa',
				'surface-lowest': '#ffffff',
				'surface-container-lowest': '#ffffff',
				'surface-container-low': '#f3f4f5',
				'surface-container': '#edeeef',
				'surface-container-high': '#e7e8e9',
				'surface-container-highest': '#e1e3e4',
				'on-surface': '#191c1d',
				'on-surface-variant': '#41484a',
				'surface-variant': '#e1e3e4',
				'surface-tint': '#3d6470',
				outline: '#71787b',
				'outline-variant': '#c1c8ca',
				'inverse-surface': '#2e3132',
				'inverse-on-surface': '#f0f1f2',
				background: '#f8f9fa',
				'on-background': '#191c1d',
			},
			fontFamily: {
				'display-lg': ['var(--font-literata)', 'Georgia', 'serif'],
				'headline-lg': ['var(--font-literata)', 'Georgia', 'serif'],
				'headline-lg-mobile': ['var(--font-literata)', 'Georgia', 'serif'],
				'headline-md': ['var(--font-literata)', 'Georgia', 'serif'],
				'body-lg': ['var(--font-inter)', 'system-ui', 'sans-serif'],
				'body-md': ['var(--font-inter)', 'system-ui', 'sans-serif'],
				'body-sm': ['var(--font-inter)', 'system-ui', 'sans-serif'],
				'label-md': ['var(--font-inter)', 'system-ui', 'sans-serif'],
				'label-sm': ['var(--font-inter)', 'system-ui', 'sans-serif'],
			},
			fontSize: {
				'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
				'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
				'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
				'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
				'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
				'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
				'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
				'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
				'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
			},
			spacing: {
				gutter: '24px',
				base: '8px',
				'margin-mobile': '16px',
				'margin-desktop': '32px',
				'container-max': '1280px',
			},
			maxWidth: {
				'container-max': '1280px',
			},
		},
	},
	plugins: [],
} satisfies Config;
